# SPDX-License-Identifier: EUPL-1.2
name: 'Cleanup ZAD Deployment'
description: 'Remove a ZAD deployment and optionally clean up GitHub resources (environments, deployments, container images)'
author: 'RijksICTGilde'

branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  api-key:
    description: 'ZAD API key (ZAD_API_KEY secret)'
    required: true
  project-id:
    description: 'ZAD project identifier (e.g., regel-k4c)'
    required: true
  deployment-name:
    description: 'Name of the deployment to delete'
    required: true
  delete-github-env:
    description: 'Delete the GitHub environment (requires github-admin-token)'
    required: false
    default: 'false'
  delete-github-deployments:
    description: 'Delete GitHub deployments for this environment (requires github-token with deployments:write)'
    required: false
    default: 'false'
  delete-container:
    description: 'Delete the container image from GHCR'
    required: false
    default: 'false'
  container-org:
    description: 'Organization owning the container (for image deletion)'
    required: false
    default: ''
  container-name:
    description: 'Container package name (for image deletion)'
    required: false
    default: ''
  container-tag:
    description: 'Container tag to delete (for image deletion)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for deployment/PR operations (defaults to automatic token)'
    required: false
    default: '${{ github.token }}'
  github-admin-token:
    description: 'GitHub token for environment deletion (needs repo admin permission, typically GITHUB_ADMIN_TOKEN secret)'
    required: false
    default: ''
  api-base-url:
    description: 'ZAD Operations Manager API base URL'
    required: false
    default: 'https://operations-manager.rig.prd1.gn2.quattro.rijksapps.nl/api'
  delete-pr-comment:
    description: 'Delete the deploy PR comment (requires github-token with pull-requests:write)'
    required: false
    default: 'true'
  comment-header:
    description: 'Header of the deploy comment to find and delete (default: "## 🚀 Preview Deployment")'
    required: false
    default: '## 🚀 Preview Deployment'
  skip-bot-prs:
    description: 'Skip cleanup for PRs created by bots (dependabot, renovate, pre-commit-ci, etc.)'
    required: false
    default: 'true'
  max-retries:
    description: 'Maximum number of retries for transient ZAD API errors (0 to disable)'
    required: false
    default: '3'
  retry-delay:
    description: 'Initial retry delay in seconds (doubles each retry)'
    required: false
    default: '2'

outputs:
  zad-deleted:
    description: 'Whether the ZAD deployment was deleted'
    value: ${{ steps.delete-zad.outputs.deleted }}
  github-env-deleted:
    description: 'Whether the GitHub environment was deleted'
    value: ${{ steps.delete-github-env.outputs.deleted }}
  github-deployments-deleted:
    description: 'Whether GitHub deployments were deleted'
    value: ${{ steps.delete-github-deployments.outputs.deleted }}
  container-deleted:
    description: 'Whether the container image was deleted'
    value: ${{ steps.delete-container.outputs.deleted }}
  pr-comment-deleted:
    description: 'Whether the PR comment was deleted'
    value: ${{ steps.delete-pr-comment.outputs.deleted }}
  skipped:
    description: 'Whether cleanup was skipped due to bot PR detection'
    value: ${{ steps.bot-check.outputs.skipped == 'true' && 'true' || 'false' }}

runs:
  using: 'composite'
  steps:
    - name: Check for bot PR
      id: bot-check
      if: inputs.skip-bot-prs == 'true' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
      shell: bash
      env:
        PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        PR_AUTHOR_TYPE: ${{ github.event.pull_request.user.type }}
      run: |
        KNOWN_BOTS=("dependabot[bot]" "renovate[bot]" "pre-commit-ci[bot]" "github-actions[bot]")
        if [ "$PR_AUTHOR_TYPE" = "Bot" ]; then
          echo "::notice::Skipping: PR author '$PR_AUTHOR' is a bot (type: $PR_AUTHOR_TYPE)"
          echo "skipped=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        for bot in "${KNOWN_BOTS[@]}"; do
          if [ "$PR_AUTHOR" = "$bot" ]; then
            echo "::notice::Skipping: PR author '$PR_AUTHOR' is a known bot"
            echo "skipped=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        done
        echo "skipped=false" >> "$GITHUB_OUTPUT"

    - name: Delete ZAD Deployment
      id: delete-zad
      if: steps.bot-check.outputs.skipped != 'true'
      shell: bash
      env:
        ZAD_API_KEY: ${{ inputs.api-key }}
        PROJECT_ID: ${{ inputs.project-id }}
        DEPLOYMENT_NAME: ${{ inputs.deployment-name }}
        API_BASE_URL: ${{ inputs.api-base-url }}
        MAX_RETRIES: ${{ inputs.max-retries }}
        RETRY_DELAY: ${{ inputs.retry-delay }}
      run: |
        # Validate inputs FIRST (before logging)
        # Allow alphanumeric, hyphens, underscores, and dots
        if ! echo "$PROJECT_ID" | grep -qE '^[a-zA-Z0-9._-]+$'; then
          echo "Error: project-id contains invalid characters (allowed: a-z, A-Z, 0-9, ., _, -)"
          exit 1
        fi
        if ! echo "$DEPLOYMENT_NAME" | grep -qE '^[a-zA-Z0-9._-]+$'; then
          echo "Error: deployment-name contains invalid characters (allowed: a-z, A-Z, 0-9, ., _, -)"
          exit 1
        fi
        if ! echo "$MAX_RETRIES" | grep -qE '^[0-9]+$'; then
          echo "Error: max-retries must be a non-negative integer"
          exit 1
        fi
        if ! echo "$RETRY_DELAY" | grep -qE '^[0-9]+$'; then
          echo "Error: retry-delay must be a non-negative integer"
          exit 1
        fi

        # Now safe to log
        echo "Deleting ZAD deployment: $DEPLOYMENT_NAME from project: $PROJECT_ID"

        # Retry helper: curl_with_retry URL [curl_args...]
        # Uses MAX_RETRIES and RETRY_DELAY from environment.
        # Sets FINAL_HTTP_CODE and FINAL_BODY after completion.
        curl_with_retry() {
          local url="$1"; shift
          local attempt=0
          local delay="$RETRY_DELAY"
          while true; do
            local response
            response=$(curl -s -w "\n%{http_code}" --max-time 60 "$@" "$url")
            FINAL_HTTP_CODE=$(echo "$response" | tail -n1)
            FINAL_BODY=$(echo "$response" | sed '$d')

            # Success
            if [ "$FINAL_HTTP_CODE" -ge 200 ] && [ "$FINAL_HTTP_CODE" -lt 300 ]; then
              return 0
            fi

            # Determine if retryable
            local retryable=false
            if [ "$FINAL_HTTP_CODE" -eq 000 ] || [ "$FINAL_HTTP_CODE" -eq 429 ]; then
              retryable=true
            elif [ "$FINAL_HTTP_CODE" -ge 500 ] && [ "$FINAL_HTTP_CODE" -le 504 ]; then
              retryable=true
            fi

            if [ "$retryable" = "true" ] && [ "$attempt" -lt "$MAX_RETRIES" ]; then
              attempt=$((attempt + 1))
              echo "::warning::Transient error (HTTP $FINAL_HTTP_CODE), retrying in ${delay}s (attempt $attempt/$MAX_RETRIES)..."
              sleep "$delay"
              delay=$((delay * 2))
              continue
            fi

            # Non-retryable or retries exhausted
            return 1
          done
        }

        if curl_with_retry "$API_BASE_URL/projects/$PROJECT_ID/$DEPLOYMENT_NAME" \
            -X DELETE \
            -H "X-API-Key: $ZAD_API_KEY"; then
          echo "ZAD deployment deleted successfully (HTTP $FINAL_HTTP_CODE)"
          echo "deleted=true" >> "$GITHUB_OUTPUT"
        else
          if [ "$FINAL_HTTP_CODE" -eq 404 ]; then
            echo "ZAD deployment not found (already deleted?)"
            echo "deleted=false" >> "$GITHUB_OUTPUT"
          elif [ "$FINAL_HTTP_CODE" -eq 000 ]; then
            echo "::warning::Unable to connect to ZAD API - network issue or API unavailable"
            echo "deleted=false" >> "$GITHUB_OUTPUT"
          elif [ "$FINAL_HTTP_CODE" -eq 401 ]; then
            echo "::warning::Authentication failed (HTTP 401) - verify ZAD_API_KEY is correct"
            echo "deleted=false" >> "$GITHUB_OUTPUT"
          elif [ "$FINAL_HTTP_CODE" -eq 403 ]; then
            echo "::warning::Access denied (HTTP 403) - API key may lack permission for project '$PROJECT_ID'"
            echo "deleted=false" >> "$GITHUB_OUTPUT"
          else
            echo "::warning::Failed to delete ZAD deployment (HTTP $FINAL_HTTP_CODE)"
            echo "$FINAL_BODY"
            echo "deleted=false" >> "$GITHUB_OUTPUT"
          fi
        fi

    - name: Delete GitHub Deployments
      id: delete-github-deployments
      if: steps.bot-check.outputs.skipped != 'true' && inputs.delete-github-deployments == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        DEPLOYMENT_NAME: ${{ inputs.deployment-name }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        echo "Deleting GitHub deployments for environment: $DEPLOYMENT_NAME"

        # Get all deployments for this environment
        DEPLOYMENTS=$(gh api "repos/$GITHUB_REPOSITORY/deployments?environment=$DEPLOYMENT_NAME" --jq '.[].id' 2>/dev/null || echo "")

        if [ -z "$DEPLOYMENTS" ]; then
          echo "No GitHub deployments found for environment: $DEPLOYMENT_NAME"
          echo "deleted=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        DELETED_COUNT=0
        for DEPLOYMENT_ID in $DEPLOYMENTS; do
          echo "Deleting deployment: $DEPLOYMENT_ID"

          # First, mark deployment as inactive
          gh api "repos/$GITHUB_REPOSITORY/deployments/$DEPLOYMENT_ID/statuses" \
            -X POST \
            -f state=inactive \
            2>/dev/null || true

          # Then delete the deployment
          if gh api "repos/$GITHUB_REPOSITORY/deployments/$DEPLOYMENT_ID" -X DELETE 2>/dev/null; then
            echo "Deleted deployment: $DEPLOYMENT_ID"
            DELETED_COUNT=$((DELETED_COUNT + 1))
          else
            echo "Failed to delete deployment: $DEPLOYMENT_ID (may already be deleted)"
          fi
        done

        echo "Deleted $DELETED_COUNT GitHub deployment(s)"
        if [ "$DELETED_COUNT" -gt 0 ]; then
          echo "deleted=true" >> "$GITHUB_OUTPUT"
        else
          echo "deleted=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Delete GitHub Environment
      id: delete-github-env
      if: steps.bot-check.outputs.skipped != 'true' && inputs.delete-github-env == 'true' && inputs.github-admin-token != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-admin-token }}
        DEPLOYMENT_NAME: ${{ inputs.deployment-name }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        echo "Deleting GitHub environment: $DEPLOYMENT_NAME"

        # URL-encode the environment name
        ENCODED_ENV=$(echo "$DEPLOYMENT_NAME" | jq -sRr @uri)

        # Try to delete and capture the response
        HTTP_RESPONSE=$(gh api "repos/$GITHUB_REPOSITORY/environments/$ENCODED_ENV" \
          -X DELETE \
          --include \
          2>&1) || true

        # Check if it was successful (204 No Content) or environment didn't exist (404)
        if echo "$HTTP_RESPONSE" | grep -q "HTTP/2 204\|HTTP/1.1 204"; then
          echo "GitHub environment '$DEPLOYMENT_NAME' deleted successfully"
          echo "deleted=true" >> "$GITHUB_OUTPUT"
        elif echo "$HTTP_RESPONSE" | grep -q "HTTP/2 404\|HTTP/1.1 404"; then
          echo "GitHub environment '$DEPLOYMENT_NAME' does not exist (already deleted?)"
          echo "deleted=false" >> "$GITHUB_OUTPUT"
          echo "reason=not_found" >> "$GITHUB_OUTPUT"
        elif echo "$HTTP_RESPONSE" | grep -q "HTTP/2 403\|HTTP/1.1 403"; then
          echo "::error::Permission denied: github-admin-token lacks permission to delete environments"
          echo "::error::Ensure the token has 'repo' scope or is a GitHub App with 'administration:write' permission"
          echo "deleted=false" >> "$GITHUB_OUTPUT"
          echo "reason=permission_denied" >> "$GITHUB_OUTPUT"
        else
          echo "::warning::Failed to delete GitHub environment '$DEPLOYMENT_NAME'"
          echo "Response: $HTTP_RESPONSE"
          echo "deleted=false" >> "$GITHUB_OUTPUT"
          echo "reason=unknown" >> "$GITHUB_OUTPUT"
        fi

    - name: Delete Container Image
      id: delete-container
      if: steps.bot-check.outputs.skipped != 'true' && inputs.delete-container == 'true' && inputs.container-org != '' && inputs.container-name != '' && inputs.container-tag != ''
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        CONTAINER_ORG: ${{ inputs.container-org }}
        CONTAINER_NAME: ${{ inputs.container-name }}
        CONTAINER_TAG: ${{ inputs.container-tag }}
      run: |
        # Validate container inputs FIRST (before using in API calls)
        if ! echo "$CONTAINER_ORG" | grep -qE '^[a-zA-Z0-9._-]+$'; then
          echo "Error: container-org contains invalid characters (allowed: a-z, A-Z, 0-9, ., _, -)"
          exit 1
        fi
        if ! echo "$CONTAINER_NAME" | grep -qE '^[a-zA-Z0-9._-]+$'; then
          echo "Error: container-name contains invalid characters (allowed: a-z, A-Z, 0-9, ., _, -)"
          exit 1
        fi
        # Container tags can have more characters but NOT quotes or backticks
        if echo "$CONTAINER_TAG" | grep -qE '["`'\''\\]'; then
          echo "Error: container-tag contains dangerous characters (quotes, backticks, backslashes not allowed)"
          exit 1
        fi

        echo "Deleting container image: ghcr.io/$CONTAINER_ORG/$CONTAINER_NAME:$CONTAINER_TAG"

        # Get all versions of the package and filter by tag using jq safely
        # Use jq --arg to safely pass the tag value
        VERSIONS=$(gh api "orgs/$CONTAINER_ORG/packages/container/$CONTAINER_NAME/versions" 2>/dev/null | \
          jq -r --arg tag "$CONTAINER_TAG" '.[] | select(.metadata.container.tags | index($tag)) | .id' 2>/dev/null || echo "")

        if [ -z "$VERSIONS" ]; then
          echo "Container image not found or no matching tag"
          echo "deleted=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        DELETED=false
        for VERSION_ID in $VERSIONS; do
          echo "Deleting version: $VERSION_ID"

          # Capture both stdout and stderr to detect "last tagged version" error
          DELETE_OUTPUT=$(gh api "orgs/$CONTAINER_ORG/packages/container/$CONTAINER_NAME/versions/$VERSION_ID" -X DELETE 2>&1)
          DELETE_RESULT=$?

          if [ $DELETE_RESULT -eq 0 ]; then
            echo "Deleted container version: $VERSION_ID"
            DELETED=true
          else
            echo "$DELETE_OUTPUT"

            # Check if this is the "last tagged version" error
            if echo "$DELETE_OUTPUT" | grep -q "You cannot delete the last tagged version"; then
              echo "This is the last tagged version. Deleting entire package instead..."

              # Delete the entire package
              if gh api "orgs/$CONTAINER_ORG/packages/container/$CONTAINER_NAME" -X DELETE 2>&1; then
                echo "Successfully deleted entire package: $CONTAINER_NAME"
                DELETED=true
              else
                echo "::warning::Failed to delete entire package: $CONTAINER_NAME"
              fi
            else
              echo "Failed to delete version: $VERSION_ID"
            fi
          fi
        done

        echo "deleted=$DELETED" >> "$GITHUB_OUTPUT"

    - name: Delete PR Comment
      id: delete-pr-comment
      if: steps.bot-check.outputs.skipped != 'true' && inputs.delete-pr-comment == 'true' && github.event_name == 'pull_request'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        COMMENT_HEADER: ${{ inputs.comment-header }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        # Find existing comment by header
        COMMENT_ID=$(gh api "repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
          --jq ".[] | select(.body | startswith(\"${COMMENT_HEADER}\")) | .id" \
          2>/dev/null | head -n1 || echo "")

        if [ -z "$COMMENT_ID" ]; then
          echo "No existing deploy comment found with header: ${COMMENT_HEADER}"
          echo "deleted=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "Deleting PR comment (ID: $COMMENT_ID)"
        if gh api "repos/${GITHUB_REPOSITORY}/issues/comments/${COMMENT_ID}" -X DELETE 2>/dev/null; then
          echo "PR comment deleted successfully"
          echo "deleted=true" >> "$GITHUB_OUTPUT"
        else
          echo "::warning::Failed to delete PR comment"
          echo "deleted=false" >> "$GITHUB_OUTPUT"
        fi
